Don't assume squeezed.begin() is a pointer
It could be a fat iterator. From MSVC:

  geometry.impl.hpp(35,1): error C2440: 'initializing':
    cannot convert from 'std::_Array_iterator<_Ty,2>' to 'int *'